exports.watchlist = [
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "41300 CE",
    "code": "BANKNIFTY2311241300CE",
    "strikeZone": "ITM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 41300,
    "ltp": 967.85,
    "token": 10416898,
    "enableTicker": true,
    "range": -9,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2341300CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "41400 CE",
    "code": "BANKNIFTY2311241400CE",
    "strikeZone": "ITM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 41400,
    "ltp": 870.05,
    "token": 10417410,
    "enableTicker": true,
    "range": -8,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2341400CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "41500 CE",
    "code": "BANKNIFTY2311241500CE",
    "strikeZone": "ITM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 41500,
    "ltp": 773.5,
    "token": 10418690,
    "enableTicker": true,
    "range": -7,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2341500CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "41600 CE",
    "code": "BANKNIFTY2311241600CE",
    "strikeZone": "ITM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 41600,
    "ltp": 684.9,
    "token": 10419202,
    "enableTicker": true,
    "range": -6,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2341600CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "41700 CE",
    "code": "BANKNIFTY2311241700CE",
    "strikeZone": "ITM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 41700,
    "ltp": 592.0,
    "token": 10419970,
    "enableTicker": true,
    "range": -5,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2341700CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "41800 CE",
    "code": "BANKNIFTY2311241800CE",
    "strikeZone": "ITM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 41800,
    "ltp": 499.9,
    "token": 10420994,
    "enableTicker": true,
    "range": -4,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2341800CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "41900 CE",
    "code": "BANKNIFTY2311241900CE",
    "strikeZone": "ITM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 41900,
    "ltp": 418.85,
    "token": 10421762,
    "enableTicker": true,
    "range": -3,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2341900CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42000 CE",
    "code": "BANKNIFTY2311242000CE",
    "strikeZone": "ITM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 42000,
    "ltp": 338.35,
    "token": 10422274,
    "enableTicker": true,
    "range": -2,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2342000CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42100 CE",
    "code": "BANKNIFTY2311242100CE",
    "strikeZone": "ITM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 42100,
    "ltp": 267.6,
    "token": 10422786,
    "enableTicker": true,
    "range": -1,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2342100CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42200 CE",
    "code": "BANKNIFTY2311242200CE",
    "strikeZone": "ATM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 42200,
    "ltp": 204.1,
    "token": 10423810,
    "enableTicker": true,
    "range": 0,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2342200CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42300 CE",
    "code": "BANKNIFTY2311242300CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 42300,
    "ltp": 151.7,
    "token": 10424322,
    "enableTicker": true,
    "range": 1,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2342300CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42400 CE",
    "code": "BANKNIFTY2311242400CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 42400,
    "ltp": 108.2,
    "token": 10424834,
    "enableTicker": true,
    "range": 2,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2342400CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42500 CE",
    "code": "BANKNIFTY2311242500CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 42500,
    "ltp": 76.3,
    "token": 10425346,
    "enableTicker": true,
    "range": 3,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2342500CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42600 CE",
    "code": "BANKNIFTY2311242600CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 42600,
    "ltp": 51.55,
    "token": 10426114,
    "enableTicker": true,
    "range": 4,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2342600CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42700 CE",
    "code": "BANKNIFTY2311242700CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 42700,
    "ltp": 34.45,
    "token": 10426626,
    "enableTicker": true,
    "range": 5,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2342700CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42800 CE",
    "code": "BANKNIFTY2311242800CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 42800,
    "ltp": 22.8,
    "token": 10427394,
    "enableTicker": true,
    "range": 6,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2342800CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42900 CE",
    "code": "BANKNIFTY2311242900CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 42900,
    "ltp": 15.55,
    "token": 10427906,
    "enableTicker": true,
    "range": 7,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2342900CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "43000 CE",
    "code": "BANKNIFTY2311243000CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 43000,
    "ltp": 11.0,
    "token": 10428418,
    "enableTicker": true,
    "range": 8,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2343000CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "43100 CE",
    "code": "BANKNIFTY2311243100CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 43100,
    "ltp": 8.3,
    "token": 10428930,
    "enableTicker": true,
    "range": 9,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2343100CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "43200 CE",
    "code": "BANKNIFTY2311243200CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 43200,
    "ltp": 6.85,
    "token": 10429442,
    "enableTicker": true,
    "range": 10,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2343200CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "43200 PE",
    "code": "BANKNIFTY2311243200PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 43200,
    "ltp": 946.5,
    "token": 10429698,
    "enableTicker": true,
    "range": 10,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2343200PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "43100 PE",
    "code": "BANKNIFTY2311243100PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 43100,
    "ltp": 853.5,
    "token": 10429186,
    "enableTicker": true,
    "range": 9,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2343100PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "43000 PE",
    "code": "BANKNIFTY2311243000PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 43000,
    "ltp": 756.5,
    "token": 10428674,
    "enableTicker": true,
    "range": 8,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2343000PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42900 PE",
    "code": "BANKNIFTY2311242900PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 42900,
    "ltp": 655.05,
    "token": 10428162,
    "enableTicker": true,
    "range": 7,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2342900PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42800 PE",
    "code": "BANKNIFTY2311242800PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 42800,
    "ltp": 566.6,
    "token": 10427650,
    "enableTicker": true,
    "range": 6,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2342800PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42700 PE",
    "code": "BANKNIFTY2311242700PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 42700,
    "ltp": 475.15,
    "token": 10427138,
    "enableTicker": true,
    "range": 5,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2342700PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42600 PE",
    "code": "BANKNIFTY2311242600PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 42600,
    "ltp": 396.0,
    "token": 10426370,
    "enableTicker": true,
    "range": 4,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2342600PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42500 PE",
    "code": "BANKNIFTY2311242500PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 42500,
    "ltp": 318.9,
    "token": 10425602,
    "enableTicker": true,
    "range": 3,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2342500PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42400 PE",
    "code": "BANKNIFTY2311242400PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 42400,
    "ltp": 251.75,
    "token": 10425090,
    "enableTicker": true,
    "range": 2,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2342400PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42300 PE",
    "code": "BANKNIFTY2311242300PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 42300,
    "ltp": 194.1,
    "token": 10424578,
    "enableTicker": true,
    "range": 1,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2342300PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42200 PE",
    "code": "BANKNIFTY2311242200PE",
    "strikeZone": "ATM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 42200,
    "ltp": 147.35,
    "token": 10424066,
    "enableTicker": true,
    "range": 0,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2342200PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42100 PE",
    "code": "BANKNIFTY2311242100PE",
    "strikeZone": "OTM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 42100,
    "ltp": 109.4,
    "token": 10423042,
    "enableTicker": true,
    "range": -1,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2342100PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42000 PE",
    "code": "BANKNIFTY2311242000PE",
    "strikeZone": "OTM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 42000,
    "ltp": 82.35,
    "token": 10422530,
    "enableTicker": true,
    "range": -2,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2342000PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "41900 PE",
    "code": "BANKNIFTY2311241900PE",
    "strikeZone": "OTM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 41900,
    "ltp": 61.15,
    "token": 10422018,
    "enableTicker": true,
    "range": -3,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2341900PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "41800 PE",
    "code": "BANKNIFTY2311241800PE",
    "strikeZone": "OTM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 41800,
    "ltp": 45.55,
    "token": 10421250,
    "enableTicker": true,
    "range": -4,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2341800PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "41700 PE",
    "code": "BANKNIFTY2311241700PE",
    "strikeZone": "OTM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 41700,
    "ltp": 33.3,
    "token": 10420738,
    "enableTicker": true,
    "range": -5,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2341700PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "41600 PE",
    "code": "BANKNIFTY2311241600PE",
    "strikeZone": "OTM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 41600,
    "ltp": 25.45,
    "token": 10419458,
    "enableTicker": true,
    "range": -6,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2341600PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "41500 PE",
    "code": "BANKNIFTY2311241500PE",
    "strikeZone": "OTM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 41500,
    "ltp": 19.25,
    "token": 10418946,
    "enableTicker": true,
    "range": -7,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2341500PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "41400 PE",
    "code": "BANKNIFTY2311241400PE",
    "strikeZone": "OTM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 41400,
    "ltp": 15.0,
    "token": 10417666,
    "enableTicker": true,
    "range": -8,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2341400PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "41300 PE",
    "code": "BANKNIFTY2311241300PE",
    "strikeZone": "OTM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "BANKNIFTY",
    "strike": 41300,
    "ltp": 11.4,
    "token": 10417154,
    "enableTicker": true,
    "range": -9,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "BANKNIFTY12JAN2341300PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "41800 CE",
    "code": "BANKNIFTY2311941800CE",
    "strikeZone": "ITM",
    "type": "CE",
    "expiry": "23119",
    "instrument": "BANKNIFTY",
    "strike": 41800,
    "ltp": 739.05,
    "token": 11459330,
    "enableTicker": true,
    "range": -4,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "N",
      "name": "NextWeekly"
    },
    "a1Expiry": "19JAN23",
    "a1Code": "BANKNIFTY19JAN2341800CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "41900 CE",
    "code": "BANKNIFTY2311941900CE",
    "strikeZone": "ITM",
    "type": "CE",
    "expiry": "23119",
    "instrument": "BANKNIFTY",
    "strike": 41900,
    "ltp": 673.25,
    "token": 11459842,
    "enableTicker": true,
    "range": -3,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "N",
      "name": "NextWeekly"
    },
    "a1Expiry": "19JAN23",
    "a1Code": "BANKNIFTY19JAN2341900CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42000 CE",
    "code": "BANKNIFTY2311942000CE",
    "strikeZone": "ITM",
    "type": "CE",
    "expiry": "23119",
    "instrument": "BANKNIFTY",
    "strike": 42000,
    "ltp": 600.2,
    "token": 11460354,
    "enableTicker": true,
    "range": -2,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "N",
      "name": "NextWeekly"
    },
    "a1Expiry": "19JAN23",
    "a1Code": "BANKNIFTY19JAN2342000CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42100 CE",
    "code": "BANKNIFTY2311942100CE",
    "strikeZone": "ITM",
    "type": "CE",
    "expiry": "23119",
    "instrument": "BANKNIFTY",
    "strike": 42100,
    "ltp": 534.6,
    "token": 11463426,
    "enableTicker": true,
    "range": -1,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "N",
      "name": "NextWeekly"
    },
    "a1Expiry": "19JAN23",
    "a1Code": "BANKNIFTY19JAN2342100CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42200 CE",
    "code": "BANKNIFTY2311942200CE",
    "strikeZone": "ATM",
    "type": "CE",
    "expiry": "23119",
    "instrument": "BANKNIFTY",
    "strike": 42200,
    "ltp": 477.4,
    "token": 11463938,
    "enableTicker": true,
    "range": 0,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "N",
      "name": "NextWeekly"
    },
    "a1Expiry": "19JAN23",
    "a1Code": "BANKNIFTY19JAN2342200CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42300 CE",
    "code": "BANKNIFTY2311942300CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23119",
    "instrument": "BANKNIFTY",
    "strike": 42300,
    "ltp": 423.65,
    "token": 11464450,
    "enableTicker": true,
    "range": 1,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "N",
      "name": "NextWeekly"
    },
    "a1Expiry": "19JAN23",
    "a1Code": "BANKNIFTY19JAN2342300CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42400 CE",
    "code": "BANKNIFTY2311942400CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23119",
    "instrument": "BANKNIFTY",
    "strike": 42400,
    "ltp": 372.8,
    "token": 11468546,
    "enableTicker": true,
    "range": 2,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "N",
      "name": "NextWeekly"
    },
    "a1Expiry": "19JAN23",
    "a1Code": "BANKNIFTY19JAN2342400CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42500 CE",
    "code": "BANKNIFTY2311942500CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23119",
    "instrument": "BANKNIFTY",
    "strike": 42500,
    "ltp": 323.6,
    "token": 11469058,
    "enableTicker": true,
    "range": 3,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "N",
      "name": "NextWeekly"
    },
    "a1Expiry": "19JAN23",
    "a1Code": "BANKNIFTY19JAN2342500CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42600 CE",
    "code": "BANKNIFTY2311942600CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23119",
    "instrument": "BANKNIFTY",
    "strike": 42600,
    "ltp": 281.3,
    "token": 11469826,
    "enableTicker": true,
    "range": 4,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "N",
      "name": "NextWeekly"
    },
    "a1Expiry": "19JAN23",
    "a1Code": "BANKNIFTY19JAN2342600CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42700 CE",
    "code": "BANKNIFTY2311942700CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23119",
    "instrument": "BANKNIFTY",
    "strike": 42700,
    "ltp": 243.4,
    "token": 11470338,
    "enableTicker": true,
    "range": 5,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "N",
      "name": "NextWeekly"
    },
    "a1Expiry": "19JAN23",
    "a1Code": "BANKNIFTY19JAN2342700CE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42700 PE",
    "code": "BANKNIFTY2311942700PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23119",
    "instrument": "BANKNIFTY",
    "strike": 42700,
    "ltp": 625.1,
    "token": 11470850,
    "enableTicker": true,
    "range": 5,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "N",
      "name": "NextWeekly"
    },
    "a1Expiry": "19JAN23",
    "a1Code": "BANKNIFTY19JAN2342700PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42600 PE",
    "code": "BANKNIFTY2311942600PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23119",
    "instrument": "BANKNIFTY",
    "strike": 42600,
    "ltp": 563.25,
    "token": 11470082,
    "enableTicker": true,
    "range": 4,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "N",
      "name": "NextWeekly"
    },
    "a1Expiry": "19JAN23",
    "a1Code": "BANKNIFTY19JAN2342600PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42500 PE",
    "code": "BANKNIFTY2311942500PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23119",
    "instrument": "BANKNIFTY",
    "strike": 42500,
    "ltp": 511.5,
    "token": 11469314,
    "enableTicker": true,
    "range": 3,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "N",
      "name": "NextWeekly"
    },
    "a1Expiry": "19JAN23",
    "a1Code": "BANKNIFTY19JAN2342500PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42400 PE",
    "code": "BANKNIFTY2311942400PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23119",
    "instrument": "BANKNIFTY",
    "strike": 42400,
    "ltp": 451.25,
    "token": 11468802,
    "enableTicker": true,
    "range": 2,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "N",
      "name": "NextWeekly"
    },
    "a1Expiry": "19JAN23",
    "a1Code": "BANKNIFTY19JAN2342400PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42300 PE",
    "code": "BANKNIFTY2311942300PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23119",
    "instrument": "BANKNIFTY",
    "strike": 42300,
    "ltp": 405.65,
    "token": 11464706,
    "enableTicker": true,
    "range": 1,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "N",
      "name": "NextWeekly"
    },
    "a1Expiry": "19JAN23",
    "a1Code": "BANKNIFTY19JAN2342300PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42200 PE",
    "code": "BANKNIFTY2311942200PE",
    "strikeZone": "ATM",
    "type": "PE",
    "expiry": "23119",
    "instrument": "BANKNIFTY",
    "strike": 42200,
    "ltp": 362.25,
    "token": 11464194,
    "enableTicker": true,
    "range": 0,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "N",
      "name": "NextWeekly"
    },
    "a1Expiry": "19JAN23",
    "a1Code": "BANKNIFTY19JAN2342200PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42100 PE",
    "code": "BANKNIFTY2311942100PE",
    "strikeZone": "OTM",
    "type": "PE",
    "expiry": "23119",
    "instrument": "BANKNIFTY",
    "strike": 42100,
    "ltp": 320.8,
    "token": 11463682,
    "enableTicker": true,
    "range": -1,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "N",
      "name": "NextWeekly"
    },
    "a1Expiry": "19JAN23",
    "a1Code": "BANKNIFTY19JAN2342100PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "42000 PE",
    "code": "BANKNIFTY2311942000PE",
    "strikeZone": "OTM",
    "type": "PE",
    "expiry": "23119",
    "instrument": "BANKNIFTY",
    "strike": 42000,
    "ltp": 285.55,
    "token": 11461122,
    "enableTicker": true,
    "range": -2,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "N",
      "name": "NextWeekly"
    },
    "a1Expiry": "19JAN23",
    "a1Code": "BANKNIFTY19JAN2342000PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "41900 PE",
    "code": "BANKNIFTY2311941900PE",
    "strikeZone": "OTM",
    "type": "PE",
    "expiry": "23119",
    "instrument": "BANKNIFTY",
    "strike": 41900,
    "ltp": 248.35,
    "token": 11460098,
    "enableTicker": true,
    "range": -3,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "N",
      "name": "NextWeekly"
    },
    "a1Expiry": "19JAN23",
    "a1Code": "BANKNIFTY19JAN2341900PE"
  },
  {
    "index": {
      "code": "NIFTY BANK",
      "lotSize": 25,
      "token": 260105,
      "multiplier": 100,
      "defaultLoad": 40,
      "factor": 4,
      "expiry": "THURSDAY",
      "freezeLimit": 900,
      "symbol": "BANKNIFTY"
    },
    "name": "41800 PE",
    "code": "BANKNIFTY2311941800PE",
    "strikeZone": "OTM",
    "type": "PE",
    "expiry": "23119",
    "instrument": "BANKNIFTY",
    "strike": 41800,
    "ltp": 219.3,
    "token": 11459586,
    "enableTicker": true,
    "range": -4,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "N",
      "name": "NextWeekly"
    },
    "a1Expiry": "19JAN23",
    "a1Code": "BANKNIFTY19JAN2341800PE"
  },
  {
    "index": {
      "code": "NIFTY 50",
      "lotSize": 50,
      "token": 256265,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "THURSDAY",
      "freezeLimit": 1800,
      "symbol": "NIFTY"
    },
    "name": "18150 PE",
    "code": "NIFTY2311218150PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "NIFTY",
    "strike": 18150,
    "ltp": 248.6,
    "token": 12731650,
    "enableTicker": true,
    "range": 5,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "NIFTY12JAN2318150PE"
  },
  {
    "index": {
      "code": "NIFTY 50",
      "lotSize": 50,
      "token": 256265,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "THURSDAY",
      "freezeLimit": 1800,
      "symbol": "NIFTY"
    },
    "name": "18100 PE",
    "code": "NIFTY2311218100PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "NIFTY",
    "strike": 18100,
    "ltp": 203.0,
    "token": 12731138,
    "enableTicker": true,
    "range": 4,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "NIFTY12JAN2318100PE"
  },
  {
    "index": {
      "code": "NIFTY 50",
      "lotSize": 50,
      "token": 256265,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "THURSDAY",
      "freezeLimit": 1800,
      "symbol": "NIFTY"
    },
    "name": "18050 PE",
    "code": "NIFTY2311218050PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "NIFTY",
    "strike": 18050,
    "ltp": 158.45,
    "token": 12730626,
    "enableTicker": true,
    "range": 3,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "NIFTY12JAN2318050PE"
  },
  {
    "index": {
      "code": "NIFTY 50",
      "lotSize": 50,
      "token": 256265,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "THURSDAY",
      "freezeLimit": 1800,
      "symbol": "NIFTY"
    },
    "name": "18000 PE",
    "code": "NIFTY2311218000PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "NIFTY",
    "strike": 18000,
    "ltp": 120.45,
    "token": 12724738,
    "enableTicker": true,
    "range": 2,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "NIFTY12JAN2318000PE"
  },
  {
    "index": {
      "code": "NIFTY 50",
      "lotSize": 50,
      "token": 256265,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "THURSDAY",
      "freezeLimit": 1800,
      "symbol": "NIFTY"
    },
    "name": "17950 PE",
    "code": "NIFTY2311217950PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "NIFTY",
    "strike": 17950,
    "ltp": 85.4,
    "token": 12724226,
    "enableTicker": true,
    "range": 1,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "NIFTY12JAN2317950PE"
  },
  {
    "index": {
      "code": "NIFTY 50",
      "lotSize": 50,
      "token": 256265,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "THURSDAY",
      "freezeLimit": 1800,
      "symbol": "NIFTY"
    },
    "name": "17900 PE",
    "code": "NIFTY2311217900PE",
    "strikeZone": "ATM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "NIFTY",
    "strike": 17900,
    "ltp": 58.25,
    "token": 12723714,
    "enableTicker": true,
    "range": 0,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "NIFTY12JAN2317900PE"
  },
  {
    "index": {
      "code": "NIFTY 50",
      "lotSize": 50,
      "token": 256265,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "THURSDAY",
      "freezeLimit": 1800,
      "symbol": "NIFTY"
    },
    "name": "17850 PE",
    "code": "NIFTY2311217850PE",
    "strikeZone": "OTM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "NIFTY",
    "strike": 17850,
    "ltp": 37.9,
    "token": 12723202,
    "enableTicker": true,
    "range": -1,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "NIFTY12JAN2317850PE"
  },
  {
    "index": {
      "code": "NIFTY 50",
      "lotSize": 50,
      "token": 256265,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "THURSDAY",
      "freezeLimit": 1800,
      "symbol": "NIFTY"
    },
    "name": "17800 PE",
    "code": "NIFTY2311217800PE",
    "strikeZone": "OTM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "NIFTY",
    "strike": 17800,
    "ltp": 23.95,
    "token": 12722690,
    "enableTicker": true,
    "range": -2,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "NIFTY12JAN2317800PE"
  },
  {
    "index": {
      "code": "NIFTY 50",
      "lotSize": 50,
      "token": 256265,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "THURSDAY",
      "freezeLimit": 1800,
      "symbol": "NIFTY"
    },
    "name": "17750 PE",
    "code": "NIFTY2311217750PE",
    "strikeZone": "OTM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "NIFTY",
    "strike": 17750,
    "ltp": 14.2,
    "token": 12722178,
    "enableTicker": true,
    "range": -3,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "NIFTY12JAN2317750PE"
  },
  {
    "index": {
      "code": "NIFTY 50",
      "lotSize": 50,
      "token": 256265,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "THURSDAY",
      "freezeLimit": 1800,
      "symbol": "NIFTY"
    },
    "name": "17700 PE",
    "code": "NIFTY2311217700PE",
    "strikeZone": "OTM",
    "type": "PE",
    "expiry": "23112",
    "instrument": "NIFTY",
    "strike": 17700,
    "ltp": 8.4,
    "token": 12721666,
    "enableTicker": true,
    "range": -4,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "NIFTY12JAN2317700PE"
  },
  {
    "index": {
      "code": "NIFTY 50",
      "lotSize": 50,
      "token": 256265,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "THURSDAY",
      "freezeLimit": 1800,
      "symbol": "NIFTY"
    },
    "name": "17700 CE",
    "code": "NIFTY2311217700CE",
    "strikeZone": "ITM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "NIFTY",
    "strike": 17700,
    "ltp": 214.9,
    "token": 12721410,
    "enableTicker": true,
    "range": -4,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "NIFTY12JAN2317700CE"
  },
  {
    "index": {
      "code": "NIFTY 50",
      "lotSize": 50,
      "token": 256265,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "THURSDAY",
      "freezeLimit": 1800,
      "symbol": "NIFTY"
    },
    "name": "17750 CE",
    "code": "NIFTY2311217750CE",
    "strikeZone": "ITM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "NIFTY",
    "strike": 17750,
    "ltp": 170.8,
    "token": 12721922,
    "enableTicker": true,
    "range": -3,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "NIFTY12JAN2317750CE"
  },
  {
    "index": {
      "code": "NIFTY 50",
      "lotSize": 50,
      "token": 256265,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "THURSDAY",
      "freezeLimit": 1800,
      "symbol": "NIFTY"
    },
    "name": "17800 CE",
    "code": "NIFTY2311217800CE",
    "strikeZone": "ITM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "NIFTY",
    "strike": 17800,
    "ltp": 130.25,
    "token": 12722434,
    "enableTicker": true,
    "range": -2,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "NIFTY12JAN2317800CE"
  },
  {
    "index": {
      "code": "NIFTY 50",
      "lotSize": 50,
      "token": 256265,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "THURSDAY",
      "freezeLimit": 1800,
      "symbol": "NIFTY"
    },
    "name": "17850 CE",
    "code": "NIFTY2311217850CE",
    "strikeZone": "ITM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "NIFTY",
    "strike": 17850,
    "ltp": 93.65,
    "token": 12722946,
    "enableTicker": true,
    "range": -1,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "NIFTY12JAN2317850CE"
  },
  {
    "index": {
      "code": "NIFTY 50",
      "lotSize": 50,
      "token": 256265,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "THURSDAY",
      "freezeLimit": 1800,
      "symbol": "NIFTY"
    },
    "name": "17900 CE",
    "code": "NIFTY2311217900CE",
    "strikeZone": "ATM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "NIFTY",
    "strike": 17900,
    "ltp": 63.75,
    "token": 12723458,
    "enableTicker": true,
    "range": 0,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "NIFTY12JAN2317900CE"
  },
  {
    "index": {
      "code": "NIFTY 50",
      "lotSize": 50,
      "token": 256265,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "THURSDAY",
      "freezeLimit": 1800,
      "symbol": "NIFTY"
    },
    "name": "17950 CE",
    "code": "NIFTY2311217950CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "NIFTY",
    "strike": 17950,
    "ltp": 42.55,
    "token": 12723970,
    "enableTicker": true,
    "range": 1,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "NIFTY12JAN2317950CE"
  },
  {
    "index": {
      "code": "NIFTY 50",
      "lotSize": 50,
      "token": 256265,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "THURSDAY",
      "freezeLimit": 1800,
      "symbol": "NIFTY"
    },
    "name": "18000 CE",
    "code": "NIFTY2311218000CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "NIFTY",
    "strike": 18000,
    "ltp": 26.75,
    "token": 12724482,
    "enableTicker": true,
    "range": 2,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "NIFTY12JAN2318000CE"
  },
  {
    "index": {
      "code": "NIFTY 50",
      "lotSize": 50,
      "token": 256265,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "THURSDAY",
      "freezeLimit": 1800,
      "symbol": "NIFTY"
    },
    "name": "18050 CE",
    "code": "NIFTY2311218050CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "NIFTY",
    "strike": 18050,
    "ltp": 16.15,
    "token": 12727042,
    "enableTicker": true,
    "range": 3,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "NIFTY12JAN2318050CE"
  },
  {
    "index": {
      "code": "NIFTY 50",
      "lotSize": 50,
      "token": 256265,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "THURSDAY",
      "freezeLimit": 1800,
      "symbol": "NIFTY"
    },
    "name": "18100 CE",
    "code": "NIFTY2311218100CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "NIFTY",
    "strike": 18100,
    "ltp": 9.7,
    "token": 12730882,
    "enableTicker": true,
    "range": 4,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "NIFTY12JAN2318100CE"
  },
  {
    "index": {
      "code": "NIFTY 50",
      "lotSize": 50,
      "token": 256265,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "THURSDAY",
      "freezeLimit": 1800,
      "symbol": "NIFTY"
    },
    "name": "18150 CE",
    "code": "NIFTY2311218150CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23112",
    "instrument": "NIFTY",
    "strike": 18150,
    "ltp": 5.8,
    "token": 12731394,
    "enableTicker": true,
    "range": 5,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "12JAN23",
    "a1Code": "NIFTY12JAN2318150CE"
  },
  {
    "index": {
      "code": "NIFTY FIN SERVICE",
      "lotSize": 40,
      "token": 257801,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "TUESDAY",
      "freezeLimit": 1800,
      "symbol": "FINNIFTY"
    },
    "name": "18350 CE",
    "code": "FINNIFTY2311718350CE",
    "strikeZone": "ITM",
    "type": "CE",
    "expiry": "23117",
    "instrument": "FINNIFTY",
    "strike": 18350,
    "ltp": 306.45,
    "token": 13498370,
    "enableTicker": true,
    "range": -4,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "17JAN23",
    "a1Code": "FINNIFTY17JAN2318350CE"
  },
  {
    "index": {
      "code": "NIFTY FIN SERVICE",
      "lotSize": 40,
      "token": 257801,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "TUESDAY",
      "freezeLimit": 1800,
      "symbol": "FINNIFTY"
    },
    "name": "18400 CE",
    "code": "FINNIFTY2311718400CE",
    "strikeZone": "ITM",
    "type": "CE",
    "expiry": "23117",
    "instrument": "FINNIFTY",
    "strike": 18400,
    "ltp": 271.1,
    "token": 13498882,
    "enableTicker": true,
    "range": -3,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "17JAN23",
    "a1Code": "FINNIFTY17JAN2318400CE"
  },
  {
    "index": {
      "code": "NIFTY FIN SERVICE",
      "lotSize": 40,
      "token": 257801,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "TUESDAY",
      "freezeLimit": 1800,
      "symbol": "FINNIFTY"
    },
    "name": "18450 CE",
    "code": "FINNIFTY2311718450CE",
    "strikeZone": "ITM",
    "type": "CE",
    "expiry": "23117",
    "instrument": "FINNIFTY",
    "strike": 18450,
    "ltp": 234.15,
    "token": 13500418,
    "enableTicker": true,
    "range": -2,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "17JAN23",
    "a1Code": "FINNIFTY17JAN2318450CE"
  },
  {
    "index": {
      "code": "NIFTY FIN SERVICE",
      "lotSize": 40,
      "token": 257801,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "TUESDAY",
      "freezeLimit": 1800,
      "symbol": "FINNIFTY"
    },
    "name": "18500 CE",
    "code": "FINNIFTY2311718500CE",
    "strikeZone": "ITM",
    "type": "CE",
    "expiry": "23117",
    "instrument": "FINNIFTY",
    "strike": 18500,
    "ltp": 202.2,
    "token": 13503234,
    "enableTicker": true,
    "range": -1,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "17JAN23",
    "a1Code": "FINNIFTY17JAN2318500CE"
  },
  {
    "index": {
      "code": "NIFTY FIN SERVICE",
      "lotSize": 40,
      "token": 257801,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "TUESDAY",
      "freezeLimit": 1800,
      "symbol": "FINNIFTY"
    },
    "name": "18550 CE",
    "code": "FINNIFTY2311718550CE",
    "strikeZone": "ATM",
    "type": "CE",
    "expiry": "23117",
    "instrument": "FINNIFTY",
    "strike": 18550,
    "ltp": 172.35,
    "token": 13505026,
    "enableTicker": true,
    "range": 0,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "17JAN23",
    "a1Code": "FINNIFTY17JAN2318550CE"
  },
  {
    "index": {
      "code": "NIFTY FIN SERVICE",
      "lotSize": 40,
      "token": 257801,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "TUESDAY",
      "freezeLimit": 1800,
      "symbol": "FINNIFTY"
    },
    "name": "18600 CE",
    "code": "FINNIFTY2311718600CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23117",
    "instrument": "FINNIFTY",
    "strike": 18600,
    "ltp": 144.1,
    "token": 13507586,
    "enableTicker": true,
    "range": 1,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "17JAN23",
    "a1Code": "FINNIFTY17JAN2318600CE"
  },
  {
    "index": {
      "code": "NIFTY FIN SERVICE",
      "lotSize": 40,
      "token": 257801,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "TUESDAY",
      "freezeLimit": 1800,
      "symbol": "FINNIFTY"
    },
    "name": "18650 CE",
    "code": "FINNIFTY2311718650CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23117",
    "instrument": "FINNIFTY",
    "strike": 18650,
    "ltp": 118.5,
    "token": 13508098,
    "enableTicker": true,
    "range": 2,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "17JAN23",
    "a1Code": "FINNIFTY17JAN2318650CE"
  },
  {
    "index": {
      "code": "NIFTY FIN SERVICE",
      "lotSize": 40,
      "token": 257801,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "TUESDAY",
      "freezeLimit": 1800,
      "symbol": "FINNIFTY"
    },
    "name": "18700 CE",
    "code": "FINNIFTY2311718700CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23117",
    "instrument": "FINNIFTY",
    "strike": 18700,
    "ltp": 96.8,
    "token": 13508610,
    "enableTicker": true,
    "range": 3,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "17JAN23",
    "a1Code": "FINNIFTY17JAN2318700CE"
  },
  {
    "index": {
      "code": "NIFTY FIN SERVICE",
      "lotSize": 40,
      "token": 257801,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "TUESDAY",
      "freezeLimit": 1800,
      "symbol": "FINNIFTY"
    },
    "name": "18750 CE",
    "code": "FINNIFTY2311718750CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23117",
    "instrument": "FINNIFTY",
    "strike": 18750,
    "ltp": 77.8,
    "token": 13509378,
    "enableTicker": true,
    "range": 4,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "17JAN23",
    "a1Code": "FINNIFTY17JAN2318750CE"
  },
  {
    "index": {
      "code": "NIFTY FIN SERVICE",
      "lotSize": 40,
      "token": 257801,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "TUESDAY",
      "freezeLimit": 1800,
      "symbol": "FINNIFTY"
    },
    "name": "18800 CE",
    "code": "FINNIFTY2311718800CE",
    "strikeZone": "OTM",
    "type": "CE",
    "expiry": "23117",
    "instrument": "FINNIFTY",
    "strike": 18800,
    "ltp": 62.15,
    "token": 13510146,
    "enableTicker": true,
    "range": 5,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "17JAN23",
    "a1Code": "FINNIFTY17JAN2318800CE"
  },
  {
    "index": {
      "code": "NIFTY FIN SERVICE",
      "lotSize": 40,
      "token": 257801,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "TUESDAY",
      "freezeLimit": 1800,
      "symbol": "FINNIFTY"
    },
    "name": "18800 PE",
    "code": "FINNIFTY2311718800PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23117",
    "instrument": "FINNIFTY",
    "strike": 18800,
    "ltp": 281.7,
    "token": 13510402,
    "enableTicker": true,
    "range": 5,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "17JAN23",
    "a1Code": "FINNIFTY17JAN2318800PE"
  },
  {
    "index": {
      "code": "NIFTY FIN SERVICE",
      "lotSize": 40,
      "token": 257801,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "TUESDAY",
      "freezeLimit": 1800,
      "symbol": "FINNIFTY"
    },
    "name": "18750 PE",
    "code": "FINNIFTY2311718750PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23117",
    "instrument": "FINNIFTY",
    "strike": 18750,
    "ltp": 246.4,
    "token": 13509634,
    "enableTicker": true,
    "range": 4,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "17JAN23",
    "a1Code": "FINNIFTY17JAN2318750PE"
  },
  {
    "index": {
      "code": "NIFTY FIN SERVICE",
      "lotSize": 40,
      "token": 257801,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "TUESDAY",
      "freezeLimit": 1800,
      "symbol": "FINNIFTY"
    },
    "name": "18700 PE",
    "code": "FINNIFTY2311718700PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23117",
    "instrument": "FINNIFTY",
    "strike": 18700,
    "ltp": 216.0,
    "token": 13508866,
    "enableTicker": true,
    "range": 3,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "17JAN23",
    "a1Code": "FINNIFTY17JAN2318700PE"
  },
  {
    "index": {
      "code": "NIFTY FIN SERVICE",
      "lotSize": 40,
      "token": 257801,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "TUESDAY",
      "freezeLimit": 1800,
      "symbol": "FINNIFTY"
    },
    "name": "18650 PE",
    "code": "FINNIFTY2311718650PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23117",
    "instrument": "FINNIFTY",
    "strike": 18650,
    "ltp": 186.45,
    "token": 13508354,
    "enableTicker": true,
    "range": 2,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "17JAN23",
    "a1Code": "FINNIFTY17JAN2318650PE"
  },
  {
    "index": {
      "code": "NIFTY FIN SERVICE",
      "lotSize": 40,
      "token": 257801,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "TUESDAY",
      "freezeLimit": 1800,
      "symbol": "FINNIFTY"
    },
    "name": "18600 PE",
    "code": "FINNIFTY2311718600PE",
    "strikeZone": "ITM",
    "type": "PE",
    "expiry": "23117",
    "instrument": "FINNIFTY",
    "strike": 18600,
    "ltp": 159.55,
    "token": 13507842,
    "enableTicker": true,
    "range": 1,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "17JAN23",
    "a1Code": "FINNIFTY17JAN2318600PE"
  },
  {
    "index": {
      "code": "NIFTY FIN SERVICE",
      "lotSize": 40,
      "token": 257801,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "TUESDAY",
      "freezeLimit": 1800,
      "symbol": "FINNIFTY"
    },
    "name": "18550 PE",
    "code": "FINNIFTY2311718550PE",
    "strikeZone": "ATM",
    "type": "PE",
    "expiry": "23117",
    "instrument": "FINNIFTY",
    "strike": 18550,
    "ltp": 140.85,
    "token": 13505282,
    "enableTicker": true,
    "range": 0,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "17JAN23",
    "a1Code": "FINNIFTY17JAN2318550PE"
  },
  {
    "index": {
      "code": "NIFTY FIN SERVICE",
      "lotSize": 40,
      "token": 257801,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "TUESDAY",
      "freezeLimit": 1800,
      "symbol": "FINNIFTY"
    },
    "name": "18500 PE",
    "code": "FINNIFTY2311718500PE",
    "strikeZone": "OTM",
    "type": "PE",
    "expiry": "23117",
    "instrument": "FINNIFTY",
    "strike": 18500,
    "ltp": 118.75,
    "token": 13503490,
    "enableTicker": true,
    "range": -1,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "17JAN23",
    "a1Code": "FINNIFTY17JAN2318500PE"
  },
  {
    "index": {
      "code": "NIFTY FIN SERVICE",
      "lotSize": 40,
      "token": 257801,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "TUESDAY",
      "freezeLimit": 1800,
      "symbol": "FINNIFTY"
    },
    "name": "18450 PE",
    "code": "FINNIFTY2311718450PE",
    "strikeZone": "OTM",
    "type": "PE",
    "expiry": "23117",
    "instrument": "FINNIFTY",
    "strike": 18450,
    "ltp": 102.05,
    "token": 13500674,
    "enableTicker": true,
    "range": -2,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "17JAN23",
    "a1Code": "FINNIFTY17JAN2318450PE"
  },
  {
    "index": {
      "code": "NIFTY FIN SERVICE",
      "lotSize": 40,
      "token": 257801,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "TUESDAY",
      "freezeLimit": 1800,
      "symbol": "FINNIFTY"
    },
    "name": "18400 PE",
    "code": "FINNIFTY2311718400PE",
    "strikeZone": "OTM",
    "type": "PE",
    "expiry": "23117",
    "instrument": "FINNIFTY",
    "strike": 18400,
    "ltp": 87.05,
    "token": 13499138,
    "enableTicker": true,
    "range": -3,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "17JAN23",
    "a1Code": "FINNIFTY17JAN2318400PE"
  },
  {
    "index": {
      "code": "NIFTY FIN SERVICE",
      "lotSize": 40,
      "token": 257801,
      "multiplier": 50,
      "defaultLoad": 10,
      "factor": 2,
      "expiry": "TUESDAY",
      "freezeLimit": 1800,
      "symbol": "FINNIFTY"
    },
    "name": "18350 PE",
    "code": "FINNIFTY2311718350PE",
    "strikeZone": "OTM",
    "type": "PE",
    "expiry": "23117",
    "instrument": "FINNIFTY",
    "strike": 18350,
    "ltp": 73.9,
    "token": 13498626,
    "enableTicker": true,
    "range": -4,
    "checked": false,
    "lots": null,
    "expiryType": {
      "code": "C",
      "name": "CurrentWeekly"
    },
    "a1Expiry": "17JAN23",
    "a1Code": "FINNIFTY17JAN2318350PE"
  }
]